[package]
name = "fff-ude-macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
base64 = "0.22"
itertools = "0.12"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }
