[package]
name = "fff-ude-example-gzip"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
fff-ude = { workspace = true }
wasm-test-encoders = { path = "../wasm-test-encoders" }
