[package]
name = "fff-format"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
flatc-rust = { workspace = true }
